name: "Deploy Jekyll Site Without Tokens"

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read  # No write permissions

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install Ruby and dependencies
      - name: Set up Ruby
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo apt-add-repository -y ppa:brightbox/ruby-ng
          sudo apt update
          sudo apt install -y ruby3.1 ruby3.1-dev
          gem install bundler

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: bundle install

      # Step 4: Build the Jekyll site
      - name: Build the site
        run: bundle exec jekyll build

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout --orphan gh-pages
          git --work-tree=_site add --all
          git --work-tree=_site commit -m "Deploy site [skip ci]"
          git push --force origin gh-pages
        env:
          JEKYLL_ENV: production
